version: '3.8'

services:
  rental_app_12:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8081:8081"
    volumes:
      - .:/var/www/html
    depends_on:
      - rental_db_12
      - mailhog

  rental_db_12:
    image: mariadb:10.5.8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=house_rental
      - MYSQL_ROOT_PASSWORD=root_password
      - DB_PORT=3306
    volumes:
      - pgd_rental_maria_data:/var/lib/mysql

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  pgd_rental_maria_data: